set tabstop=4
set softtabstop=4
set expandtab
set shiftwidth=4
set smarttab
syntax enable
set number
set fixeol
set smartindent
set mouse=a
set clipboard+=unnamedplus
set linebreak
set showmatch
set splitright
colorscheme catppuccin_mocha

