set tabstop=4
set softtabstop=4
set expandtab
set shiftwidth=4
set smarttab
syntax enable
set number
set fixeol
set smartindent
set mouse=a
set clipboard+=unnamedplus
set linebreak
set showmatch
set splitright
set termguicolors
colorscheme catppuccin_mocha
set noshowmode
set laststatus=2
if &term =~ '^foot'
    " options to make vim behave like it would if $TERM was xterm-256color
    " colors
    let &t_8f = "\<Esc>[38:2:%lu:%lu:%lum"
    let &t_8b = "\<Esc>[48:2:%lu:%lu:%lum"    
    " ctrl+arrow
    execute "set <xUp>=\e[1;*A"
    execute "set <xDown>=\e[1;*B"
    execute "set <xRight>=\e[1;*C"
    execute "set <xLeft>=\e[1;*D"
    " mouse
    set ttymouse=xterm2
endif
